//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermeco.Multimarcas.Services.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hermeconpiprd.hermeco.local:50000/XISOAPAdapter/MessageServlet?senderParty" +
            "=&senderService=SAP_I_MODELO_BS&receiverParty=&receiverService=&interface=CreaPe" +
            "dido_Sync_Out&interfaceNamespace=urn%3AcreaPedido%3Amodelo%3Asap")]
        public string Hermeco_Multimarcas_Services_wsPedidos_CreaPedido_Sync_OutService {
            get {
                return ((string)(this["Hermeco_Multimarcas_Services_wsPedidos_CreaPedido_Sync_OutService"]));
            }
        }
    }
}
