//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermeco.Multimarcas.Services.HPedidos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HPedidos.wsPedidosSoap")]
    public interface wsPedidosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GuardarPedido(string strPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarPedido", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GuardarPedidoAsync(string strPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresarPedido_TiendaVirtual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IngresarPedido_TiendaVirtual(string strOrdenDeCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresarPedido_TiendaVirtual", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IngresarPedido_TiendaVirtualAsync(string strOrdenDeCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarTarifaTransporteXPoblacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        decimal ConsultarTarifaTransporteXPoblacion(decimal decMontoCompra, int intCodigoPoblacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarTarifaTransporteXPoblacion", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> ConsultarTarifaTransporteXPoblacionAsync(decimal decMontoCompra, int intCodigoPoblacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarOrdenCompra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ingresarOrdenCompra(string nitCliente, string numeroOC, string xmlMensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ingresarOrdenCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ingresarOrdenCompraAsync(string nitCliente, string numeroOC, string xmlMensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarOrdenCompra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool actualizarOrdenCompra(string nitCliente, string numeroOC, string xmlMensaje, string strEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarOrdenCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> actualizarOrdenCompraAsync(string nitCliente, string numeroOC, string xmlMensaje, string strEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarOrdenCompra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string consultarOrdenCompra(string numeroOC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultarOrdenCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<string> consultarOrdenCompraAsync(string numeroOC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarEstadoOrdenCompra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ActualizarEstadoOrdenCompra(string DocumentoCliente, string NumeroOrden, string EstadoOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarEstadoOrdenCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ActualizarEstadoOrdenCompraAsync(string DocumentoCliente, string NumeroOrden, string EstadoOrden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerConsecutivoOrdenCompra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ObtenerConsecutivoOrdenCompra();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerConsecutivoOrdenCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ObtenerConsecutivoOrdenCompraAsync();
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerOrdenesDeCompraXCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteResponse ObtenerOrdenesDeCompraXCliente(Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerOrdenesDeCompraXCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteResponse> ObtenerOrdenesDeCompraXClienteAsync(Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ObtenerOrdenesDeCompraXClienteResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TD_Cliente clienteField;
        
        private TD_Orden[] ordenesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TD_Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("Cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("orden", IsNullable=false)]
        public TD_Orden[] Ordenes {
            get {
                return this.ordenesField;
            }
            set {
                this.ordenesField = value;
                this.RaisePropertyChanged("Ordenes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TD_Cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentoClienteField;
        
        private string tipoDocumentiField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string documentoCliente {
            get {
                return this.documentoClienteField;
            }
            set {
                this.documentoClienteField = value;
                this.RaisePropertyChanged("documentoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tipoDocumenti {
            get {
                return this.tipoDocumentiField;
            }
            set {
                this.tipoDocumentiField = value;
                this.RaisePropertyChanged("tipoDocumenti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TD_Direccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoField;
        
        private string nombreField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private int idPoblacionField;
        
        private string reservado1Field;
        
        private string reservado2Field;
        
        private string reservado3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdPoblacion {
            get {
                return this.idPoblacionField;
            }
            set {
                this.idPoblacionField = value;
                this.RaisePropertyChanged("IdPoblacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Reservado1 {
            get {
                return this.reservado1Field;
            }
            set {
                this.reservado1Field = value;
                this.RaisePropertyChanged("Reservado1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Reservado2 {
            get {
                return this.reservado2Field;
            }
            set {
                this.reservado2Field = value;
                this.RaisePropertyChanged("Reservado2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Reservado3 {
            get {
                return this.reservado3Field;
            }
            set {
                this.reservado3Field = value;
                this.RaisePropertyChanged("Reservado3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TD_Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoPluField;
        
        private string codigoReferenciaField;
        
        private string descReferenciaField;
        
        private string descTallaField;
        
        private string descColorField;
        
        private decimal precioField;
        
        private int cantidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoPlu {
            get {
                return this.codigoPluField;
            }
            set {
                this.codigoPluField = value;
                this.RaisePropertyChanged("codigoPlu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoReferencia {
            get {
                return this.codigoReferenciaField;
            }
            set {
                this.codigoReferenciaField = value;
                this.RaisePropertyChanged("codigoReferencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descReferencia {
            get {
                return this.descReferenciaField;
            }
            set {
                this.descReferenciaField = value;
                this.RaisePropertyChanged("descReferencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string descTalla {
            get {
                return this.descTallaField;
            }
            set {
                this.descTallaField = value;
                this.RaisePropertyChanged("descTalla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string descColor {
            get {
                return this.descColorField;
            }
            set {
                this.descColorField = value;
                this.RaisePropertyChanged("descColor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TD_EncOrdenCompra : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroOrdenCompraField;
        
        private System.DateTime fechaOrdenCompraField;
        
        private string estadoField;
        
        private string numeroPedidoField;
        
        private System.DateTime fechaDespachoField;
        
        private string numeroFacturaField;
        
        private string numeroGuiaField;
        
        private string transportadoraField;
        
        private string estadoGuiaField;
        
        private System.DateTime fechaEntregaField;
        
        private decimal totalCompraField;
        
        private decimal totalFleteField;
        
        private decimal totalImpuestoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroOrdenCompra {
            get {
                return this.numeroOrdenCompraField;
            }
            set {
                this.numeroOrdenCompraField = value;
                this.RaisePropertyChanged("numeroOrdenCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime fechaOrdenCompra {
            get {
                return this.fechaOrdenCompraField;
            }
            set {
                this.fechaOrdenCompraField = value;
                this.RaisePropertyChanged("fechaOrdenCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string numeroPedido {
            get {
                return this.numeroPedidoField;
            }
            set {
                this.numeroPedidoField = value;
                this.RaisePropertyChanged("numeroPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime fechaDespacho {
            get {
                return this.fechaDespachoField;
            }
            set {
                this.fechaDespachoField = value;
                this.RaisePropertyChanged("fechaDespacho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string numeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                this.numeroFacturaField = value;
                this.RaisePropertyChanged("numeroFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string numeroGuia {
            get {
                return this.numeroGuiaField;
            }
            set {
                this.numeroGuiaField = value;
                this.RaisePropertyChanged("numeroGuia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string transportadora {
            get {
                return this.transportadoraField;
            }
            set {
                this.transportadoraField = value;
                this.RaisePropertyChanged("transportadora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string estadoGuia {
            get {
                return this.estadoGuiaField;
            }
            set {
                this.estadoGuiaField = value;
                this.RaisePropertyChanged("estadoGuia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        public System.DateTime fechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
                this.RaisePropertyChanged("fechaEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal totalCompra {
            get {
                return this.totalCompraField;
            }
            set {
                this.totalCompraField = value;
                this.RaisePropertyChanged("totalCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal totalFlete {
            get {
                return this.totalFleteField;
            }
            set {
                this.totalFleteField = value;
                this.RaisePropertyChanged("totalFlete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal totalImpuesto {
            get {
                return this.totalImpuestoField;
            }
            set {
                this.totalImpuestoField = value;
                this.RaisePropertyChanged("totalImpuesto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TD_Orden : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TD_EncOrdenCompra encabezadoField;
        
        private TD_Producto[] producctosField;
        
        private TD_Direccion[] direccionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TD_EncOrdenCompra Encabezado {
            get {
                return this.encabezadoField;
            }
            set {
                this.encabezadoField = value;
                this.RaisePropertyChanged("Encabezado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("producto", IsNullable=false)]
        public TD_Producto[] Producctos {
            get {
                return this.producctosField;
            }
            set {
                this.producctosField = value;
                this.RaisePropertyChanged("Producctos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("direccion", IsNullable=false)]
        public TD_Direccion[] Direcciones {
            get {
                return this.direccionesField;
            }
            set {
                this.direccionesField = value;
                this.RaisePropertyChanged("Direcciones");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesDeCompraXCliente", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesDeCompraXClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strDocumentoCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strFechaInicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strFechaFinal;
        
        public ObtenerOrdenesDeCompraXClienteRequest() {
        }
        
        public ObtenerOrdenesDeCompraXClienteRequest(string strDocumentoCliente, string strFechaInicial, string strFechaFinal) {
            this.strDocumentoCliente = strDocumentoCliente;
            this.strFechaInicial = strFechaInicial;
            this.strFechaFinal = strFechaFinal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerOrdenesDeCompraXClienteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObtenerOrdenesDeCompraXClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteResult ObtenerOrdenesDeCompraXClienteResult;
        
        public ObtenerOrdenesDeCompraXClienteResponse() {
        }
        
        public ObtenerOrdenesDeCompraXClienteResponse(Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteResult ObtenerOrdenesDeCompraXClienteResult) {
            this.ObtenerOrdenesDeCompraXClienteResult = ObtenerOrdenesDeCompraXClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsPedidosSoapChannel : Hermeco.Multimarcas.Services.HPedidos.wsPedidosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsPedidosSoapClient : System.ServiceModel.ClientBase<Hermeco.Multimarcas.Services.HPedidos.wsPedidosSoap>, Hermeco.Multimarcas.Services.HPedidos.wsPedidosSoap {
        
        public wsPedidosSoapClient() {
        }
        
        public wsPedidosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsPedidosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPedidosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPedidosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GuardarPedido(string strPedido) {
            return base.Channel.GuardarPedido(strPedido);
        }
        
        public System.Threading.Tasks.Task<string> GuardarPedidoAsync(string strPedido) {
            return base.Channel.GuardarPedidoAsync(strPedido);
        }
        
        public bool IngresarPedido_TiendaVirtual(string strOrdenDeCompra) {
            return base.Channel.IngresarPedido_TiendaVirtual(strOrdenDeCompra);
        }
        
        public System.Threading.Tasks.Task<bool> IngresarPedido_TiendaVirtualAsync(string strOrdenDeCompra) {
            return base.Channel.IngresarPedido_TiendaVirtualAsync(strOrdenDeCompra);
        }
        
        public decimal ConsultarTarifaTransporteXPoblacion(decimal decMontoCompra, int intCodigoPoblacion) {
            return base.Channel.ConsultarTarifaTransporteXPoblacion(decMontoCompra, intCodigoPoblacion);
        }
        
        public System.Threading.Tasks.Task<decimal> ConsultarTarifaTransporteXPoblacionAsync(decimal decMontoCompra, int intCodigoPoblacion) {
            return base.Channel.ConsultarTarifaTransporteXPoblacionAsync(decMontoCompra, intCodigoPoblacion);
        }
        
        public bool ingresarOrdenCompra(string nitCliente, string numeroOC, string xmlMensaje) {
            return base.Channel.ingresarOrdenCompra(nitCliente, numeroOC, xmlMensaje);
        }
        
        public System.Threading.Tasks.Task<bool> ingresarOrdenCompraAsync(string nitCliente, string numeroOC, string xmlMensaje) {
            return base.Channel.ingresarOrdenCompraAsync(nitCliente, numeroOC, xmlMensaje);
        }
        
        public bool actualizarOrdenCompra(string nitCliente, string numeroOC, string xmlMensaje, string strEstado) {
            return base.Channel.actualizarOrdenCompra(nitCliente, numeroOC, xmlMensaje, strEstado);
        }
        
        public System.Threading.Tasks.Task<bool> actualizarOrdenCompraAsync(string nitCliente, string numeroOC, string xmlMensaje, string strEstado) {
            return base.Channel.actualizarOrdenCompraAsync(nitCliente, numeroOC, xmlMensaje, strEstado);
        }
        
        public string consultarOrdenCompra(string numeroOC) {
            return base.Channel.consultarOrdenCompra(numeroOC);
        }
        
        public System.Threading.Tasks.Task<string> consultarOrdenCompraAsync(string numeroOC) {
            return base.Channel.consultarOrdenCompraAsync(numeroOC);
        }
        
        public bool ActualizarEstadoOrdenCompra(string DocumentoCliente, string NumeroOrden, string EstadoOrden) {
            return base.Channel.ActualizarEstadoOrdenCompra(DocumentoCliente, NumeroOrden, EstadoOrden);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEstadoOrdenCompraAsync(string DocumentoCliente, string NumeroOrden, string EstadoOrden) {
            return base.Channel.ActualizarEstadoOrdenCompraAsync(DocumentoCliente, NumeroOrden, EstadoOrden);
        }
        
        public int ObtenerConsecutivoOrdenCompra() {
            return base.Channel.ObtenerConsecutivoOrdenCompra();
        }
        
        public System.Threading.Tasks.Task<int> ObtenerConsecutivoOrdenCompraAsync() {
            return base.Channel.ObtenerConsecutivoOrdenCompraAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteResponse Hermeco.Multimarcas.Services.HPedidos.wsPedidosSoap.ObtenerOrdenesDeCompraXCliente(Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteRequest request) {
            return base.Channel.ObtenerOrdenesDeCompraXCliente(request);
        }
        
        public Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteResult ObtenerOrdenesDeCompraXCliente(string strDocumentoCliente, string strFechaInicial, string strFechaFinal) {
            Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteRequest inValue = new Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteRequest();
            inValue.strDocumentoCliente = strDocumentoCliente;
            inValue.strFechaInicial = strFechaInicial;
            inValue.strFechaFinal = strFechaFinal;
            Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteResponse retVal = ((Hermeco.Multimarcas.Services.HPedidos.wsPedidosSoap)(this)).ObtenerOrdenesDeCompraXCliente(inValue);
            return retVal.ObtenerOrdenesDeCompraXClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteResponse> Hermeco.Multimarcas.Services.HPedidos.wsPedidosSoap.ObtenerOrdenesDeCompraXClienteAsync(Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteRequest request) {
            return base.Channel.ObtenerOrdenesDeCompraXClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteResponse> ObtenerOrdenesDeCompraXClienteAsync(string strDocumentoCliente, string strFechaInicial, string strFechaFinal) {
            Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteRequest inValue = new Hermeco.Multimarcas.Services.HPedidos.ObtenerOrdenesDeCompraXClienteRequest();
            inValue.strDocumentoCliente = strDocumentoCliente;
            inValue.strFechaInicial = strFechaInicial;
            inValue.strFechaFinal = strFechaFinal;
            return ((Hermeco.Multimarcas.Services.HPedidos.wsPedidosSoap)(this)).ObtenerOrdenesDeCompraXClienteAsync(inValue);
        }
    }
}
